align the native quickstart and 3rd party overcloud roles
Change-Id: Ie5e8e0d4a682f2678e3bfd81c289838c95729044

diff --git a/templates/overcloud-deploy.sh.j2 b/templates/overcloud-deploy.sh.j2
--- a/templates/overcloud-deploy.sh.j2
+++ b/templates/overcloud-deploy.sh.j2
@@ -55,10 +55,21 @@ openstack overcloud deploy --templates \
 # so check `heat stack-list` for a CREATE_FAILED status.
 if heat stack-list | grep -q 'CREATE_FAILED'; then
 
+    # get the failures list
+    openstack stack failures list overcloud > failed_deployment_list.log || true
+
+    # get any puppet related errors
     for failed in $(heat resource-list \
         --nested-depth 5 overcloud | grep FAILED |
         grep 'StructuredDeployment ' | cut -d '|' -f3)
-    do heat deployment-show $failed > failed_deployment_$failed.log
+    do echo -n "heat deployment-show out put for deployment: $failed" >> failed_deployments.log
+       echo -n "######################################################" >> failed_deployments.log
+       heat deployment-show $failed >> failed_deployments.log
+       echo -n "######################################################" >> failed_deployments.log
+       echo "puppet standard error for deployment: $failed" >> failed_deployments.log
+       echo -n "######################################################" >> failed_deployments.log
+       echo -e $(heat deployment-show $failed | jq -r .output_values.deploy_stderr) >> failed_deployments.log
+       echo -n "######################################################" >> failed_deployments.log
     done
 fi
 
